services:
  db:
    container_name: customer-service
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres-customer-service
    volumes:
      - db:/data/postgres-customer-service
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: